### ISSUE TITLE
Usage guidelines for `license.md`

### ISSUE THREAD

**Issue by tobiasvl** [dmg01/database#3]
The first game added to this database, µCity, has a file called `license.md` in its subdirectory which contains that game's license.

However, this file is not referenced in `CONTRIBUTE.md`.

Should all games have a file like this? Is it used for anything?

**Comment by tobiasvl** [comment]
Wait. I realized now that it's probably present in order to actually uphold the license's terms…

**Comment by avivace** [comment]
Yep, undocumentend but the license file inside the game folders serves to specify the terms under which that game/assets are released, since we are effectively rehosting it.

I'll push an update in some hours, thank you for noticing.
