### ISSUE TITLE
adjustris is not playing in the JS emulator

### ISSUE THREAD

**Issue by avivace** [dmg01/database#5]
The last entry added by @tobiasvl provides a `gb` binary not playing in the javascript emulator.

This actually raises 3 problems/todo :

- Provide a way to show games but hide the emulator (i.e. only the download link is shown). Maybe a flag `playable` in the `game.json` should be enough?
- We need a basic frontend page to allow the testing of the javascript emulator used
- Set up automatic testing on the PR, e.g. testing for the common errors (typos)

**Comment by tobiasvl** [comment]
This should be split into several issues.

To the issue related to this issue's title, perhaps try out some of the other JS emulators? The ROM plays perfectly in BGB, so the emulator itself might be inaccurate.

**Comment by avivace** [comment]
Yep, it was just a way to list things we need to add to the roadmap.

Fact is, we don't have much choice in emulators playing in the browser

**Comment by avivace** [comment]
In this context, this is fixed.

Games flagged with `onlineplay = false` won't fire up the emulator and instead will suggest downloading the ROM and playing it with BGB or Gambatte.

This needs to be reposted on our newly created [GameBoy-Online fork](https://github.com/dmg01/GameBoy-Online), where we'll try to isolate and reproduce this cases and fix them. Having a list of glitch/freeze-triggering ROM/routines will help a lot.
