### ISSUE TITLE
Dates should follow ISO 8601

### ISSUE THREAD

**Issue by tobiasvl** [dmg01/database#7]
The date in `game.json` should comply with [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`2017-12-07`) instead of the American date format (`12/07/2017`).

See also https://github.com/dmg01/homebrewhub/issues/6

**Comment by avivace** [comment]
Dates object in the json files here could be completely arbitrary, so I'll go with it.

We also expect in the near future (soon™) to have a simple and html form to easily add games, which converts the addition to a compliant PR here, so we could implement there a simple date picker, without having to force US or EU standards.
