### ISSUE TITLE
Alternative to "repository" for closed source games

### ISSUE THREAD

**Issue by tobiasvl** [dmg01/database#8]
The `repository` field is for a "Repository or URL where the source can be found", according to `CONTRIBUTE.md`.

This doesn't make much sense for games that aren't open source. Yes, the field is optional, but it would be nice to be able to link somewhere regardless.

Could this field be used to link to the homepage instead in those cases, or should we create a new `homepage` field?

(Yes, this is a bit theoretical, since this only affects games that are closed source but are still permitted to distribute as ROMs.)

**Comment by avivace** [comment]
I tend to exclude to use the same field for a general project link (in case of closed source games) and git respository, since I'm trying to use the repository field to fetch the last ROM release and offer direct link on the page.

I'm positive with adding an `homepage` field.
